version: 2

models:
  - name: stg_listings
    description: "Modèle Silver — données nettoyées et enrichies"
    columns:
      - name: listing_id
        description: "Identifiant unique de l'annonce"
        tests: [unique, not_null]
      - name: property_type
        tests: [not_null]
      - name: country
        tests: [not_null]
      - name: city
        tests: [not_null]
      - name: price
        tests: [not_null]
      - name: surface_m2
        tests: [not_null]
      - name: listing_date
        tests: [not_null]